## Dataframe of news headlines from either The Onion or HuffPost 
### Has article link, headline, and a binary column titled is_sarcastic, article line, and headline
#### is_sarcastic: 0= true news, 1=sarcastic

In [15]:
import pandas as pd

In [36]:
sarcasm1 = pd.read_json('Sarcasm_Headlines_Dataset.json', lines=True)

In [37]:
sarcasm1

,article_link,headline,is_sarcastic
0,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0
1,https://www.huffingtonpost.com/entry/roseanne-...,the 'roseanne' revival catches up to our thorn...,0
2,https://local.theonion.com/mom-starting-to-fea...,mom starting to fear son's web series closest ...,1
3,https://politics.theonion.com/boehner-just-wan...,"boehner just wants wife to listen, not come up...",1
4,https://www.huffingtonpost.com/entry/jk-rowlin...,j.k. rowling wishes snape happy birthday in th...,0
...,...,...,...
26704,https://www.huffingtonpost.com/entry/american-...,american politics in moral free-fall,0
26705,https://www.huffingtonpost.com/entry/americas-...,america's best 20 hikes,0
26706,https://www.huffingtonpost.com/entry/reparatio...,reparations and obama,0
26707,https://www.huffingtonpost.com/entry/israeli-b...,israeli ban targeting boycott supporters raise...,0
26708,https://www.huffingtonpost.com/entry/gourmet-g...,gourmet gifts for the foodie 2014,0

In [38]:
sarcasm1.headline[26708]

'gourmet gifts for the foodie 2014'

In [39]:
sarcasm2 = pd.read_json('Sarcasm_Headlines_Dataset_v2.json', lines=True)

In [40]:
sarcasm2

,is_sarcastic,headline,article_link
0,1,thirtysomething scientists unveil doomsday clo...,https://www.theonion.com/thirtysomething-scien...
1,0,dem rep. totally nails why congress is falling...,https://www.huffingtonpost.com/entry/donna-edw...
2,0,eat your veggies: 9 deliciously different recipes,https://www.huffingtonpost.com/entry/eat-your-...
3,1,inclement weather prevents liar from getting t...,https://local.theonion.com/inclement-weather-p...
4,1,mother comes pretty close to using word 'strea...,https://www.theonion.com/mother-comes-pretty-c...
...,...,...,...
28614,1,jews to celebrate rosh hashasha or something,https://www.theonion.com/jews-to-celebrate-ros...
28615,1,internal affairs investigator disappointed con...,https://local.theonion.com/internal-affairs-in...
28616,0,the most beautiful acceptance speech this week...,https://www.huffingtonpost.com/entry/andrew-ah...
28617,1,mars probe destroyed by orbiting spielberg-gat...,https://www.theonion.com/mars-probe-destroyed-...
28618,1,dad clarifies this not a food stop,https://www.theonion.com/dad-clarifies-this-no...

In [41]:
sarcasm2.headline[28616]

'the most beautiful acceptance speech this week came from a queer korean'

In [42]:
all_sarc = pd.concat([sarcasm1, sarcasm2], ignore_index=True)
all_sarc

,article_link,headline,is_sarcastic
0,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0
1,https://www.huffingtonpost.com/entry/roseanne-...,the 'roseanne' revival catches up to our thorn...,0
2,https://local.theonion.com/mom-starting-to-fea...,mom starting to fear son's web series closest ...,1
3,https://politics.theonion.com/boehner-just-wan...,"boehner just wants wife to listen, not come up...",1
4,https://www.huffingtonpost.com/entry/jk-rowlin...,j.k. rowling wishes snape happy birthday in th...,0
...,...,...,...
55323,https://www.theonion.com/jews-to-celebrate-ros...,jews to celebrate rosh hashasha or something,1
55324,https://local.theonion.com/internal-affairs-in...,internal affairs investigator disappointed con...,1
55325,https://www.huffingtonpost.com/entry/andrew-ah...,the most beautiful acceptance speech this week...,0
55326,https://www.theonion.com/mars-probe-destroyed-...,mars probe destroyed by orbiting spielberg-gat...,1
55327,https://www.theonion.com/dad-clarifies-this-no...,dad clarifies this not a food stop,1

In [43]:
sarc_headlines = pd.DataFrame([all_sarc.headline, all_sarc.is_sarcastic]).T
sarc_headlines

                                                headline is_sarcastic
0      former versace store clerk sues over secret 'b...            0
1      the 'roseanne' revival catches up to our thorn...            0
2      mom starting to fear son's web series closest ...            1
3      boehner just wants wife to listen, not come up...            1
4      j.k. rowling wishes snape happy birthday in th...            0
...                                                  ...          ...
55323       jews to celebrate rosh hashasha or something            1
55324  internal affairs investigator disappointed con...            1
55325  the most beautiful acceptance speech this week...            0
55326  mars probe destroyed by orbiting spielberg-gat...            1
55327                 dad clarifies this not a food stop            1

[55328 rows x 2 columns]

In [44]:
sarc_headlines.rename(columns={'is_sarcastic':'real_or_fake'}, inplace=True)
sarc_headlines

                                                headline real_or_fake
0      former versace store clerk sues over secret 'b...            0
1      the 'roseanne' revival catches up to our thorn...            0
2      mom starting to fear son's web series closest ...            1
3      boehner just wants wife to listen, not come up...            1
4      j.k. rowling wishes snape happy birthday in th...            0
...                                                  ...          ...
55323       jews to celebrate rosh hashasha or something            1
55324  internal affairs investigator disappointed con...            1
55325  the most beautiful acceptance speech this week...            0
55326  mars probe destroyed by orbiting spielberg-gat...            1
55327                 dad clarifies this not a food stop            1

[55328 rows x 2 columns]

In [45]:
sarc_headlines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55328 entries, 0 to 55327
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   headline      55328 non-null  object
 1   real_or_fake  55328 non-null  object
dtypes: object(2)
memory usage: 864.6+ KB

In [46]:
sarc_headlines.to_csv('sarc_headlines.csv', index=False)